### 학습지 생성 API
POST http://localhost:8080/api/v1/home-schools
Content-Type: application/json

{
  "name": "학습지 1",
  "teacherId": 1,
  "problemIds": [1, 2, 3]
}

### 학습지 출제 API
POST http://localhost:8080/api/v1/home-schools/present
Content-Type: application/json

{
  "homeSchoolId": 1,
  "studentId": [12345, 12346, 12347]
}

### 학습지 학습 통계 분석 API
GET http://localhost:8080/api/v1/home-schools/analyze/1
Content-Type: application/json
